/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/common_msgs/visualization_msgs/msg/InteractiveMarkerPose.msg */

package ros.pkg.visualization_msgs.msg;

import java.nio.ByteBuffer;

public class InteractiveMarkerPose extends ros.communication.Message {

  public ros.pkg.std_msgs.msg.Header header = new ros.pkg.std_msgs.msg.Header();
  public ros.pkg.geometry_msgs.msg.Pose pose = new ros.pkg.geometry_msgs.msg.Pose();
  public java.lang.String name = new java.lang.String();

  public InteractiveMarkerPose() {
  }

  public static java.lang.String __s_getDataType() { return "visualization_msgs/InteractiveMarkerPose"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "a6e6833209a196a38d798dadb02c81f8"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "# Time/frame info.\n" +
"Header header\n" +
"\n" +
"# Initial pose. Also, defines the pivot point for rotations.\n" +
"geometry_msgs/Pose pose\n" +
"\n" +
"# Identifying string. Must be globally unique in\n" +
"# the topic that this message is sent through.\n" +
"string name\n" +
"\n" +
"================================================================================\n" +
"MSG: std_msgs/Header\n" +
"# Standard metadata for higher-level stamped data types.\n" +
"# This is generally used to communicate timestamped data \n" +
"# in a particular coordinate frame.\n" +
"# \n" +
"# sequence ID: consecutively increasing ID \n" +
"uint32 seq\n" +
"#Two-integer timestamp that is expressed as:\n" +
"# * stamp.secs: seconds (stamp_secs) since epoch\n" +
"# * stamp.nsecs: nanoseconds since stamp_secs\n" +
"# time-handling sugar is provided by the client library\n" +
"time stamp\n" +
"#Frame this data is associated with\n" +
"# 0: no frame\n" +
"# 1: global frame\n" +
"string frame_id\n" +
"\n" +
"================================================================================\n" +
"MSG: geometry_msgs/Pose\n" +
"# A representation of pose in free space, composed of postion and orientation. \n" +
"Point position\n" +
"Quaternion orientation\n" +
"\n" +
"================================================================================\n" +
"MSG: geometry_msgs/Point\n" +
"# This contains the position of a point in free space\n" +
"float64 x\n" +
"float64 y\n" +
"float64 z\n" +
"\n" +
"================================================================================\n" +
"MSG: geometry_msgs/Quaternion\n" +
"# This represents an orientation in free space in quaternion form.\n" +
"\n" +
"float64 x\n" +
"float64 y\n" +
"float64 z\n" +
"float64 w\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public InteractiveMarkerPose clone() {
    InteractiveMarkerPose c = new InteractiveMarkerPose();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += header.serializationLength();
    __l += pose.serializationLength();
    __l += 4 + name.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    header.serialize(bb, seq);
    pose.serialize(bb, seq);
    Serialization.writeString(bb, name);
  }

  public void deserialize(ByteBuffer bb) {
    header.deserialize(bb);
    pose.deserialize(bb);
    name = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof InteractiveMarkerPose))
      return false;
    InteractiveMarkerPose other = (InteractiveMarkerPose) o;
    return
      header.equals(other.header) &&
      pose.equals(other.pose) &&
      name.equals(other.name) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.header == null ? 0 : this.header.hashCode());
    result = prime * result + (this.pose == null ? 0 : this.pose.hashCode());
    result = prime * result + (this.name == null ? 0 : this.name.hashCode());
    return result;
  }
} // class InteractiveMarkerPose

