/* Auto-generated by genmsg_cpp for file /home/uav-team3/AU-UAV-ROS/AU_UAV_stack/AU_UAV_ROS/srv/GoToWaypoint.srv */

package ros.pkg.AU_UAV_ROS.srv;

import java.nio.ByteBuffer;


public class GoToWaypoint extends ros.communication.Service<GoToWaypoint.Request, GoToWaypoint.Response> {

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/GoToWaypoint"; }
  public static java.lang.String __s_getMD5Sum() { return "c8cfaca8efcd99e3add29323eb5d2746"; }

  public java.lang.String getDataType() { return GoToWaypoint.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return GoToWaypoint.__s_getMD5Sum(); }

  public GoToWaypoint.Request createRequest() {
    return new GoToWaypoint.Request();
  }

  public GoToWaypoint.Response createResponse() {
    return new GoToWaypoint.Response();
  }

static public class Request extends ros.communication.Message {

  public short planeID;
  public double latitude;
  public double longitude;
  public double altitude;
  public boolean isAvoidanceManeuver;
  public boolean isNewQueue;

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/GoToWaypointRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "2e058964f456d53e9679e3d97faca340"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "c8cfaca8efcd99e3add29323eb5d2746"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int16 planeID\n" +
"float64 latitude\n" +
"float64 longitude\n" +
"float64 altitude\n" +
"bool isAvoidanceManeuver\n" +
"bool isNewQueue\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 2; // planeID
    __l += 8; // latitude
    __l += 8; // longitude
    __l += 8; // altitude
    __l += 1; // isAvoidanceManeuver
    __l += 1; // isNewQueue
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putShort(planeID);
    bb.putDouble(latitude);
    bb.putDouble(longitude);
    bb.putDouble(altitude);
    bb.put((byte)(isAvoidanceManeuver ? 1 : 0));
    bb.put((byte)(isNewQueue ? 1 : 0));
  }

  public void deserialize(ByteBuffer bb) {
    planeID = bb.getShort();
    latitude = bb.getDouble();
    longitude = bb.getDouble();
    altitude = bb.getDouble();
    isAvoidanceManeuver = bb.get() != 0 ? true : false;
    isNewQueue = bb.get() != 0 ? true : false;
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      planeID == other.planeID &&
      latitude == other.latitude &&
      longitude == other.longitude &&
      altitude == other.altitude &&
      isAvoidanceManeuver == other.isAvoidanceManeuver &&
      isNewQueue == other.isNewQueue &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.planeID;
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.latitude)) ^ (tmp >>> 32));
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.longitude)) ^ (tmp >>> 32));
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.altitude)) ^ (tmp >>> 32));
    result = prime * result + (this.isAvoidanceManeuver ? 1231 : 1237);
    result = prime * result + (this.isNewQueue ? 1231 : 1237);
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.lang.String error = new java.lang.String();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/GoToWaypointResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "eca8b96616c32aacf1be8bbf14c70eba"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "c8cfaca8efcd99e3add29323eb5d2746"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string error\n" +
"\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + error.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, error);
  }

  public void deserialize(ByteBuffer bb) {
    error = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      error.equals(other.error) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.error == null ? 0 : this.error.hashCode());
    return result;
  }
} // class Response

} //class

