/* Auto-generated by genmsg_cpp for file /home/uav-team3/AU-UAV-ROS/AU_UAV_stack/AU_UAV_ROS/srv/RequestWaypointInfo.srv */

package ros.pkg.AU_UAV_ROS.srv;

import java.nio.ByteBuffer;


public class RequestWaypointInfo extends ros.communication.Service<RequestWaypointInfo.Request, RequestWaypointInfo.Response> {

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/RequestWaypointInfo"; }
  public static java.lang.String __s_getMD5Sum() { return "db9e3801b1da39b7fbc4397b931e6587"; }

  public java.lang.String getDataType() { return RequestWaypointInfo.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return RequestWaypointInfo.__s_getMD5Sum(); }

  public RequestWaypointInfo.Request createRequest() {
    return new RequestWaypointInfo.Request();
  }

  public RequestWaypointInfo.Response createResponse() {
    return new RequestWaypointInfo.Response();
  }

static public class Request extends ros.communication.Message {

  public short planeID;
  public boolean isAvoidanceWaypoint;
  public short positionInQueue;

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/RequestWaypointInfoRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "2e653a234de35bdf6da6afeeb9fc6e66"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "db9e3801b1da39b7fbc4397b931e6587"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int16 planeID\n" +
"bool isAvoidanceWaypoint\n" +
"int16 positionInQueue\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 2; // planeID
    __l += 1; // isAvoidanceWaypoint
    __l += 2; // positionInQueue
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putShort(planeID);
    bb.put((byte)(isAvoidanceWaypoint ? 1 : 0));
    bb.putShort(positionInQueue);
  }

  public void deserialize(ByteBuffer bb) {
    planeID = bb.getShort();
    isAvoidanceWaypoint = bb.get() != 0 ? true : false;
    positionInQueue = bb.getShort();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      planeID == other.planeID &&
      isAvoidanceWaypoint == other.isAvoidanceWaypoint &&
      positionInQueue == other.positionInQueue &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.planeID;
    result = prime * result + (this.isAvoidanceWaypoint ? 1231 : 1237);
    result = prime * result + this.positionInQueue;
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.lang.String error = new java.lang.String();
  public double latitude;
  public double longitude;
  public double altitude;

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "AU_UAV_ROS/RequestWaypointInfoResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "1a61f6fe0ff5166e7f6ee46d444ffb8e"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "db9e3801b1da39b7fbc4397b931e6587"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string error\n" +
"float64 latitude\n" +
"float64 longitude\n" +
"float64 altitude\n" +
"\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + error.length();
    __l += 8; // latitude
    __l += 8; // longitude
    __l += 8; // altitude
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, error);
    bb.putDouble(latitude);
    bb.putDouble(longitude);
    bb.putDouble(altitude);
  }

  public void deserialize(ByteBuffer bb) {
    error = Serialization.readString(bb);
    latitude = bb.getDouble();
    longitude = bb.getDouble();
    altitude = bb.getDouble();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      error.equals(other.error) &&
      latitude == other.latitude &&
      longitude == other.longitude &&
      altitude == other.altitude &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.error == null ? 0 : this.error.hashCode());
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.latitude)) ^ (tmp >>> 32));
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.longitude)) ^ (tmp >>> 32));
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.altitude)) ^ (tmp >>> 32));
    return result;
  }
} // class Response

} //class

