/* Auto-generated by genmsg_cpp for file /opt/ros/electric/stacks/ros_comm/tools/topic_tools/srv/MuxSelect.srv */

package ros.pkg.topic_tools.srv;

import java.nio.ByteBuffer;


public class MuxSelect extends ros.communication.Service<MuxSelect.Request, MuxSelect.Response> {

  public static java.lang.String __s_getDataType() { return "topic_tools/MuxSelect"; }
  public static java.lang.String __s_getMD5Sum() { return "053052240ca985e1f2eedbb0dae9b1f7"; }

  public java.lang.String getDataType() { return MuxSelect.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return MuxSelect.__s_getMD5Sum(); }

  public MuxSelect.Request createRequest() {
    return new MuxSelect.Request();
  }

  public MuxSelect.Response createResponse() {
    return new MuxSelect.Response();
  }

static public class Request extends ros.communication.Message {

  public java.lang.String topic = new java.lang.String();

  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "topic_tools/MuxSelectRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "d8f94bae31b356b24d0427f80426d0c3"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "053052240ca985e1f2eedbb0dae9b1f7"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string topic\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + topic.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, topic);
  }

  public void deserialize(ByteBuffer bb) {
    topic = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      topic.equals(other.topic) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.topic == null ? 0 : this.topic.hashCode());
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.lang.String prev_topic = new java.lang.String();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "topic_tools/MuxSelectResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "3db0a473debdbafea387c9e49358c320"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "053052240ca985e1f2eedbb0dae9b1f7"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string prev_topic\n" +
"\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + prev_topic.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, prev_topic);
  }

  public void deserialize(ByteBuffer bb) {
    prev_topic = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      prev_topic.equals(other.prev_topic) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.prev_topic == null ? 0 : this.prev_topic.hashCode());
    return result;
  }
} // class Response

} //class

