/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Byte.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Byte extends ros.communication.Message {

  public short data;

  public Byte() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Byte"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "ad736a2e8818154c487bb80fe42ce43b"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "byte data\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Byte clone() {
    Byte c = new Byte();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 1; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.put((byte)data);
  }

  public void deserialize(ByteBuffer bb) {
    data = (short)(bb.get() & 0xff);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Byte))
      return false;
    Byte other = (Byte) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.data;
    return result;
  }
} // class Byte

