/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/ColorRGBA.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class ColorRGBA extends ros.communication.Message {

  public float r;
  public float g;
  public float b;
  public float a;

  public ColorRGBA() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/ColorRGBA"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "a29a96539573343b1310c73607334b00"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "float32 r\n" +
"float32 g\n" +
"float32 b\n" +
"float32 a\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public ColorRGBA clone() {
    ColorRGBA c = new ColorRGBA();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4; // r
    __l += 4; // g
    __l += 4; // b
    __l += 4; // a
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putFloat(r);
    bb.putFloat(g);
    bb.putFloat(b);
    bb.putFloat(a);
  }

  public void deserialize(ByteBuffer bb) {
    r = bb.getFloat();
    g = bb.getFloat();
    b = bb.getFloat();
    a = bb.getFloat();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof ColorRGBA))
      return false;
    ColorRGBA other = (ColorRGBA) o;
    return
      r == other.r &&
      g == other.g &&
      b == other.b &&
      a == other.a &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + Float.floatToIntBits(this.r);
    result = prime * result + Float.floatToIntBits(this.g);
    result = prime * result + Float.floatToIntBits(this.b);
    result = prime * result + Float.floatToIntBits(this.a);
    return result;
  }
} // class ColorRGBA

