/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Float32.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Float32 extends ros.communication.Message {

  public float data;

  public Float32() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Float32"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "73fcbf46b49191e672908e50842a83d4"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "float32 data\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Float32 clone() {
    Float32 c = new Float32();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putFloat(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.getFloat();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Float32))
      return false;
    Float32 other = (Float32) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + Float.floatToIntBits(this.data);
    return result;
  }
} // class Float32

