/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Float64.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Float64 extends ros.communication.Message {

  public double data;

  public Float64() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Float64"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "fdb28210bfa9d7c91146260178d9a584"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "float64 data\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Float64 clone() {
    Float64 c = new Float64();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 8; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putDouble(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.getDouble();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Float64))
      return false;
    Float64 other = (Float64) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (int)((tmp = Double.doubleToLongBits(this.data)) ^ (tmp >>> 32));
    return result;
  }
} // class Float64

