/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Int16.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Int16 extends ros.communication.Message {

  public short data;

  public Int16() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Int16"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "8524586e34fbd7cb1c08c5f5f1ca0e57"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int16 data\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Int16 clone() {
    Int16 c = new Int16();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 2; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putShort(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.getShort();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Int16))
      return false;
    Int16 other = (Int16) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.data;
    return result;
  }
} // class Int16

