/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Int8.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Int8 extends ros.communication.Message {

  public byte data;

  public Int8() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Int8"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "27ffa0c9c4b8fb8492252bcad9e5c57b"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "int8 data\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Int8 clone() {
    Int8 c = new Int8();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 1; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.put(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.get();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Int8))
      return false;
    Int8 other = (Int8) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + this.data;
    return result;
  }
} // class Int8

