/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/Time.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class Time extends ros.communication.Message {

  public ros.communication.Time data = new ros.communication.Time();

  public Time() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/Time"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "cd7166c74c552c311fbcc2fe5a7bc289"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "time data\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Time clone() {
    Time c = new Time();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 8; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeTime(bb, data);
  }

  public void deserialize(ByteBuffer bb) {
    data = Serialization.readTime(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Time))
      return false;
    Time other = (Time) o;
    return
      data.equals(other.data) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.data == null ? 0 : this.data.hashCode());
    return result;
  }
} // class Time

