/* Auto-generated by genmsg_java.py for file /opt/ros/electric/stacks/ros_comm/messages/std_msgs/msg/UInt64.msg */

package ros.pkg.std_msgs.msg;

import java.nio.ByteBuffer;

public class UInt64 extends ros.communication.Message {

  public long data;

  public UInt64() {
  }

  public static java.lang.String __s_getDataType() { return "std_msgs/UInt64"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "1b2a79973e8bf53d7b53acb71299cb57"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "uint64 data\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public UInt64 clone() {
    UInt64 c = new UInt64();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 8; // data
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    bb.putLong(data);
  }

  public void deserialize(ByteBuffer bb) {
    data = bb.getLong();
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof UInt64))
      return false;
    UInt64 other = (UInt64) o;
    return
      data == other.data &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (int)(this.data ^ (this.data >>> 32));
    return result;
  }
} // class UInt64

