/* Auto-generated by genmsg_cpp for file /opt/ros/electric/stacks/geometry/tf/srv/FrameGraph.srv */

package ros.pkg.tf.srv;

import java.nio.ByteBuffer;


public class FrameGraph extends ros.communication.Service<FrameGraph.Request, FrameGraph.Response> {

  public static java.lang.String __s_getDataType() { return "tf/FrameGraph"; }
  public static java.lang.String __s_getMD5Sum() { return "c4af9ac907e58e906eb0b6e3c58478c0"; }

  public java.lang.String getDataType() { return FrameGraph.__s_getDataType(); }
  public java.lang.String getMD5Sum() { return FrameGraph.__s_getMD5Sum(); }

  public FrameGraph.Request createRequest() {
    return new FrameGraph.Request();
  }

  public FrameGraph.Response createResponse() {
    return new FrameGraph.Response();
  }

static public class Request extends ros.communication.Message {


  public Request() {
  }

  public static java.lang.String __s_getDataType() { return "tf/FrameGraphRequest"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "d41d8cd98f00b204e9800998ecf8427e"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "c4af9ac907e58e906eb0b6e3c58478c0"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Request clone() {
    Request c = new Request();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
  }

  public void deserialize(ByteBuffer bb) {
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Request))
      return false;
    Request other = (Request) o;
    return
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    return result;
  }
} // class Request

static public class Response extends ros.communication.Message {

  public java.lang.String dot_graph = new java.lang.String();

  public Response() {
  }

  public static java.lang.String __s_getDataType() { return "tf/FrameGraphResponse"; }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public static java.lang.String __s_getMD5Sum() { return "c4af9ac907e58e906eb0b6e3c58478c0"; }
  public java.lang.String getMD5Sum() { return __s_getMD5Sum(); }
  public static java.lang.String __s_getServerMD5Sum() { return "c4af9ac907e58e906eb0b6e3c58478c0"; }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String __s_getMessageDefinition() { return "string dot_graph\n" +
"\n" +
"\n" +
""; }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }

  public Response clone() {
    Response c = new Response();
    c.deserialize(serialize(0));
    return c;
  }

  public void setTo(ros.communication.Message m) {
    deserialize(m.serialize(0));
  }

  public int serializationLength() {
    int __l = 0;
    __l += 4 + dot_graph.length();
    return __l;
  }

  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, dot_graph);
  }

  public void deserialize(ByteBuffer bb) {
    dot_graph = Serialization.readString(bb);
  }

  @SuppressWarnings("all")
  public boolean equals(Object o) {
    if(!(o instanceof Response))
      return false;
    Response other = (Response) o;
    return
      dot_graph.equals(other.dot_graph) &&
      true;
  }

  @SuppressWarnings("all")
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    long tmp;
    result = prime * result + (this.dot_graph == null ? 0 : this.dot_graph.hashCode());
    return result;
  }
} // class Response

} //class

